"""observations and edge validity

Revision ID: b29eccd3b9d1
Revises: 95e3784b4e2c
Create Date: 2026-09-06 19:11:05.176374
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b29eccd3b9d1"
down_revision: str | None = "95e3784b4e2c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "observations",
        sa.Column("observation_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("subject_entity_id", sa.BigInteger(), nullable=False),
        sa.Column("metric", sa.Text(), nullable=False),
        sa.Column("value_numeric", sa.Float(), nullable=True),
        sa.Column("value_text", sa.Text(), nullable=True),
        sa.Column("unit", sa.Text(), nullable=True),
        sa.Column("denominator", sa.Text(), nullable=True),
        sa.Column("geography_entity_id", sa.BigInteger(), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("method", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("supporting_chunk_ids", postgresql.ARRAY(sa.BigInteger()), nullable=False),
        sa.Column("contested_with", postgresql.ARRAY(sa.BigInteger()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("produced_by", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("quality_tier", sa.Integer(), nullable=True),
        sa.Column(
            "produced_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("schema_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "period_end IS NULL OR period_start IS NULL OR period_end >= period_start",
            name=op.f("ck_observations_period_ordered"),
        ),
        sa.CheckConstraint(
            "value_numeric IS NOT NULL OR value_text IS NOT NULL",
            name=op.f("ck_observations_has_a_value"),
        ),
        sa.ForeignKeyConstraint(
            ["geography_entity_id"],
            ["entities.entity_id"],
            name=op.f("fk_observations_geography_entity_id_entities"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["subject_entity_id"],
            ["entities.entity_id"],
            name=op.f("fk_observations_subject_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("observation_id", name=op.f("pk_observations")),
    )
    op.create_index(
        op.f("ix_observations_created_at"), "observations", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_observations_geography_entity_id"),
        "observations",
        ["geography_entity_id"],
        unique=False,
    )
    op.create_index(
        "ix_observations_metric_period", "observations", ["metric", "period_start"], unique=False
    )
    op.create_index(
        op.f("ix_observations_period_start"), "observations", ["period_start"], unique=False
    )
    op.create_index(
        op.f("ix_observations_produced_by"), "observations", ["produced_by"], unique=False
    )
    op.create_index(
        op.f("ix_observations_quality_tier"), "observations", ["quality_tier"], unique=False
    )
    op.create_index(
        "ix_observations_subject_metric",
        "observations",
        ["subject_entity_id", "metric"],
        unique=False,
    )
    op.add_column("edges", sa.Column("valid_from", sa.Date(), nullable=True))
    op.add_column("edges", sa.Column("valid_to", sa.Date(), nullable=True))
    op.create_index(op.f("ix_edges_valid_from"), "edges", ["valid_from"], unique=False)
    op.create_index(op.f("ix_edges_valid_to"), "edges", ["valid_to"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_edges_valid_to"), table_name="edges")
    op.drop_index(op.f("ix_edges_valid_from"), table_name="edges")
    op.drop_column("edges", "valid_to")
    op.drop_column("edges", "valid_from")
    op.drop_index("ix_observations_subject_metric", table_name="observations")
    op.drop_index(op.f("ix_observations_quality_tier"), table_name="observations")
    op.drop_index(op.f("ix_observations_produced_by"), table_name="observations")
    op.drop_index(op.f("ix_observations_period_start"), table_name="observations")
    op.drop_index("ix_observations_metric_period", table_name="observations")
    op.drop_index(op.f("ix_observations_geography_entity_id"), table_name="observations")
    op.drop_index(op.f("ix_observations_created_at"), table_name="observations")
    op.drop_table("observations")
    # ### end Alembic commands ###
