"""initial schema

Revision ID: 95e3784b4e2c
Revises:
Create Date: 2026-09-06 18:51:35.465536
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "95e3784b4e2c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_tokens",
        sa.Column("token_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("agent_id", sa.Text(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("allowed_tools", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("rate_limit", sa.Integer(), nullable=True),
        sa.Column("seed_cap_per_run", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("token_id", name=op.f("pk_agent_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_agent_tokens_token_hash")),
    )
    op.create_index(op.f("ix_agent_tokens_agent_id"), "agent_tokens", ["agent_id"], unique=False)
    op.create_index(
        op.f("ix_agent_tokens_created_at"), "agent_tokens", ["created_at"], unique=False
    )
    op.create_table(
        "agents",
        sa.Column("agent_id", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("task_types", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column(
            "token_scope",
            sa.Enum(
                "read", "read_write", name="token_scope", native_enum=False, create_constraint=True
            ),
            server_default="read",
            nullable=False,
        ),
        sa.Column("cost_tier", sa.Text(), nullable=True),
        sa.Column("quality_tier", sa.Integer(), nullable=True),
        sa.Column("max_context", sa.Integer(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("fallback_agent_id", sa.Text(), nullable=True),
        sa.Column("endpoint", sa.Text(), nullable=True),
        sa.Column("health_url", sa.Text(), nullable=True),
        sa.Column(
            "availability",
            sa.Enum(
                "always",
                "on_demand",
                "opportunistic",
                name="agent_availability",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="on_demand",
            nullable=False,
        ),
        sa.Column("wake_mac", sa.Text(), nullable=True),
        sa.Column("api_key_env_var", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("agent_id", name=op.f("pk_agents")),
    )
    op.create_index(op.f("ix_agents_created_at"), "agents", ["created_at"], unique=False)
    op.create_index(
        "ix_agents_enabled_quality", "agents", ["enabled", "quality_tier"], unique=False
    )
    op.create_table(
        "attribute_definitions",
        sa.Column("attribute_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "scope",
            sa.Enum(
                "global",
                "topic_local",
                name="attribute_scope",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="global",
            nullable=False,
        ),
        sa.Column("topic", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "proposed",
                "retired",
                name="attribute_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("schema_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("discrimination", sa.Float(), nullable=True),
        sa.Column("usage_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "consecutive_audit_failures", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("last_audited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("attribute_id", name=op.f("pk_attribute_definitions")),
        sa.UniqueConstraint("name", name=op.f("uq_attribute_definitions_name")),
    )
    op.create_index(
        op.f("ix_attribute_definitions_created_at"),
        "attribute_definitions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attribute_definitions_topic"), "attribute_definitions", ["topic"], unique=False
    )
    op.create_table(
        "enrichment_queue",
        sa.Column("item_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "item_type",
            sa.Enum(
                "figure_vlm",
                "ocr_quality",
                "chart_ocr",
                name="enrichment_item_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("target_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "queued",
                "running",
                "done",
                "failed",
                name="job_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("requested_by", sa.Text(), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("item_id", name=op.f("pk_enrichment_queue")),
    )
    op.create_index(
        op.f("ix_enrichment_queue_created_at"), "enrichment_queue", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_enrichment_queue_item_type"), "enrichment_queue", ["item_type"], unique=False
    )
    op.create_index(
        "ix_enrichment_status_type", "enrichment_queue", ["status", "item_type"], unique=False
    )
    op.create_table(
        "entities",
        sa.Column("entity_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column(
            "node_type",
            sa.Enum(
                "concept",
                "place",
                "organisation",
                "intervention",
                "finding",
                "source",
                "use_case",
                "odd",
                "vehicle_class",
                "service_model",
                "stakeholder",
                "failure_mode",
                "regulatory_requirement",
                "annotation",
                name="node_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("aliases", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(1024), nullable=True),
        sa.Column("topic_labels", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("merged_from", postgresql.ARRAY(sa.BigInteger()), nullable=True),
        sa.Column("redirects_to", sa.BigInteger(), nullable=True),
        sa.Column("is_annotation", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("produced_by", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("quality_tier", sa.Integer(), nullable=True),
        sa.Column(
            "produced_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("schema_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.ForeignKeyConstraint(
            ["redirects_to"],
            ["entities.entity_id"],
            name=op.f("fk_entities_redirects_to_entities"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("entity_id", name=op.f("pk_entities")),
        sa.UniqueConstraint("canonical_name", "node_type", name="uq_entities_canonical_name_type"),
    )
    op.create_index(op.f("ix_entities_created_at"), "entities", ["created_at"], unique=False)
    op.create_index(op.f("ix_entities_produced_by"), "entities", ["produced_by"], unique=False)
    op.create_index(op.f("ix_entities_quality_tier"), "entities", ["quality_tier"], unique=False)
    op.create_index(op.f("ix_entities_redirects_to"), "entities", ["redirects_to"], unique=False)
    op.create_index(
        "ix_entities_type_name", "entities", ["node_type", "canonical_name"], unique=False
    )
    op.create_table(
        "fetch_policy",
        sa.Column("domain", sa.Text(), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "blocked",
                "paused",
                name="domain_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "consecutive_failures", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_by", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("domain", name=op.f("pk_fetch_policy")),
    )
    op.create_table(
        "gazetteer",
        sa.Column("term_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("canonical", sa.Text(), nullable=False),
        sa.Column("aliases", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column(
            "entity_type",
            sa.Enum(
                "agency",
                "scheme",
                "infrastructure",
                "metric",
                "concept",
                name="gazetteer_entity_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("topic_labels", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "manual",
                "auto_acronym",
                "model_proposed",
                name="gazetteer_source",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="manual",
            nullable=False,
        ),
        sa.Column("approved", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("occurrence_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("term_id", name=op.f("pk_gazetteer")),
    )
    op.create_index(
        "ix_gazetteer_approved_type", "gazetteer", ["approved", "entity_type"], unique=False
    )
    op.create_index("ix_gazetteer_canonical", "gazetteer", ["canonical"], unique=True)
    op.create_index(op.f("ix_gazetteer_created_at"), "gazetteer", ["created_at"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("notification_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "notification_type",
            sa.Enum(
                "run_summary",
                "job_complete",
                "alert",
                "seed_proposal",
                "gazetteer_proposal",
                "merge_adjudication",
                name="notification_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("surface", sa.Text(), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("notification_id", name=op.f("pk_notifications")),
    )
    op.create_index(
        op.f("ix_notifications_created_at"), "notifications", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_notification_type"),
        "notifications",
        ["notification_type"],
        unique=False,
    )
    op.create_table(
        "queue",
        sa.Column("task_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("url_or_query", sa.Text(), nullable=False),
        sa.Column(
            "task_type",
            sa.Enum(
                "url",
                "query",
                "doi",
                "sitemap",
                name="task_type",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="url",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "fetched",
                "extracted",
                "embedded",
                "done",
                "failed",
                "rejected_duplicate",
                name="task_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("topic", sa.Text(), nullable=True),
        sa.Column(
            "seed_source",
            sa.Enum(
                "frontier",
                "model",
                "user",
                "diversity",
                name="seed_source",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="frontier",
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("task_id", name=op.f("pk_queue")),
    )
    op.create_index("ix_queue_claim", "queue", ["status", "priority", "created_at"], unique=False)
    op.create_index(op.f("ix_queue_created_at"), "queue", ["created_at"], unique=False)
    op.create_index(op.f("ix_queue_topic"), "queue", ["topic"], unique=False)
    op.create_index("ix_queue_url_or_query", "queue", ["url_or_query"], unique=False)
    op.create_table(
        "reports",
        sa.Column("job_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("question", sa.Text(), nullable=True),
        sa.Column("coverage_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "queued",
                "running",
                "done",
                "failed",
                name="job_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("output_path", sa.Text(), nullable=True),
        sa.Column("produced_by", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("quality_tier", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("job_id", name=op.f("pk_reports")),
    )
    op.create_index(op.f("ix_reports_created_at"), "reports", ["created_at"], unique=False)
    op.create_table(
        "runs",
        sa.Column("run_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "stage",
            sa.Enum(
                "pull",
                "extract",
                "tag",
                "score",
                "analogies",
                "gap",
                "seed",
                "done",
                name="run_stage",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "done",
                "failed",
                "deferred",
                name="run_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="running",
            nullable=False,
        ),
        sa.Column("last_chunk_id", sa.BigInteger(), nullable=True),
        sa.Column("agent_id", sa.Text(), nullable=True),
        sa.Column("tokens_used", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("edges_added", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("tags_added", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("seeds_emitted", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("run_id", name=op.f("pk_runs")),
    )
    op.create_index(op.f("ix_runs_started_at"), "runs", ["started_at"], unique=False)
    op.create_table(
        "sources",
        sa.Column("source_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("archive_url", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column("publisher", sa.Text(), nullable=True),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column("doi", sa.Text(), nullable=True),
        sa.Column("accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checksum", sa.Text(), nullable=True),
        sa.Column(
            "source_tier",
            sa.Enum(
                "peer_reviewed",
                "government",
                "institutional",
                "press",
                "informal",
                name="source_tier",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="informal",
            nullable=False,
        ),
        sa.Column(
            "retention_tier",
            sa.Enum(
                "primary",
                "background",
                "junk",
                name="retention_tier",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="background",
            nullable=False,
        ),
        sa.Column("raw_file_path", sa.Text(), nullable=True),
        sa.Column("language", sa.Text(), nullable=True),
        sa.Column("text_available", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("ocr_applied", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "ocr_tier",
            sa.Enum(
                "none",
                "cheap",
                "quality",
                name="ocr_tier",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="none",
            nullable=False,
        ),
        sa.Column("ocr_confidence", sa.Float(), nullable=True),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("source_id", name=op.f("pk_sources")),
        sa.UniqueConstraint("url", name="uq_sources_url"),
    )
    op.create_index(op.f("ix_sources_created_at"), "sources", ["created_at"], unique=False)
    op.create_index(op.f("ix_sources_doi"), "sources", ["doi"], unique=False)
    op.create_index(op.f("ix_sources_language"), "sources", ["language"], unique=False)
    op.create_index(
        op.f("ix_sources_publication_date"), "sources", ["publication_date"], unique=False
    )
    op.create_index(
        "ix_sources_tier_date", "sources", ["source_tier", "publication_date"], unique=False
    )
    op.create_table(
        "steering_log",
        sa.Column("log_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.Text(), nullable=False),
        sa.Column("topic", sa.Text(), nullable=True),
        sa.Column("field", sa.Text(), nullable=True),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("log_id", name=op.f("pk_steering_log")),
    )
    op.create_index(
        op.f("ix_steering_log_changed_at"), "steering_log", ["changed_at"], unique=False
    )
    op.create_index(op.f("ix_steering_log_topic"), "steering_log", ["topic"], unique=False)
    op.create_table(
        "topic_config",
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("weight", sa.Float(), server_default=sa.text("0.0"), nullable=False),
        sa.Column("floor", sa.Float(), server_default=sa.text("0.05"), nullable=False),
        sa.Column("ceiling", sa.Float(), server_default=sa.text("1.0"), nullable=False),
        sa.Column("boost_factor", sa.Float(), nullable=True),
        sa.Column("boost_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pinned", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "maintenance",
                "paused",
                "archived",
                name="topic_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("topic", name=op.f("pk_topic_config")),
    )
    op.create_table(
        "attribute_values",
        sa.Column("value_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("entity_id", sa.BigInteger(), nullable=False),
        sa.Column("attribute_id", sa.BigInteger(), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("value_numeric", sa.Float(), nullable=True),
        sa.Column("value_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("supporting_chunk_ids", postgresql.ARRAY(sa.BigInteger()), nullable=False),
        sa.Column("tagged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("produced_by", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("quality_tier", sa.Integer(), nullable=True),
        sa.Column(
            "produced_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("schema_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["attribute_definitions.attribute_id"],
            name=op.f("fk_attribute_values_attribute_id_attribute_definitions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.entity_id"],
            name=op.f("fk_attribute_values_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("value_id", name=op.f("pk_attribute_values")),
        sa.UniqueConstraint(
            "entity_id",
            "attribute_id",
            "schema_version",
            name="uq_attribute_values_entity_attribute_version",
        ),
    )
    op.create_index(
        "ix_attribute_values_attribute",
        "attribute_values",
        ["attribute_id", "entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attribute_values_created_at"), "attribute_values", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_attribute_values_produced_by"), "attribute_values", ["produced_by"], unique=False
    )
    op.create_index(
        op.f("ix_attribute_values_quality_tier"), "attribute_values", ["quality_tier"], unique=False
    )
    op.create_table(
        "chunks",
        sa.Column("chunk_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(1024), nullable=True),
        sa.Column("page_or_offset", sa.Integer(), nullable=True),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
            name=op.f("fk_chunks_source_id_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("chunk_id", name=op.f("pk_chunks")),
        sa.UniqueConstraint("source_id", "chunk_index", name="uq_chunks_source_id_chunk_index"),
    )
    op.create_index(op.f("ix_chunks_created_at"), "chunks", ["created_at"], unique=False)
    op.create_index("ix_chunks_id_created", "chunks", ["chunk_id", "created_at"], unique=False)
    op.create_table(
        "edges",
        sa.Column("edge_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("from_node", sa.BigInteger(), nullable=False),
        sa.Column("to_node", sa.BigInteger(), nullable=False),
        sa.Column("relation_type", sa.Text(), nullable=False),
        sa.Column("topic_labels", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("supporting_chunk_ids", postgresql.ARRAY(sa.BigInteger()), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "stance",
            sa.Enum(
                "supports",
                "opposes",
                "mixed",
                "neutral",
                "unclear",
                name="stance",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "certainty",
            sa.Enum(
                "hedged",
                "qualified",
                "asserted",
                "measured",
                name="certainty",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("contested_with", postgresql.ARRAY(sa.BigInteger()), nullable=True),
        sa.Column("created_by", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("produced_by", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("quality_tier", sa.Integer(), nullable=True),
        sa.Column(
            "produced_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("schema_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_node"],
            ["entities.entity_id"],
            name=op.f("fk_edges_from_node_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_node"],
            ["entities.entity_id"],
            name=op.f("fk_edges_to_node_entities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("edge_id", name=op.f("pk_edges")),
    )
    op.create_index(op.f("ix_edges_created_at"), "edges", ["created_at"], unique=False)
    op.create_index("ix_edges_from", "edges", ["from_node", "relation_type"], unique=False)
    op.create_index(op.f("ix_edges_produced_by"), "edges", ["produced_by"], unique=False)
    op.create_index(op.f("ix_edges_quality_tier"), "edges", ["quality_tier"], unique=False)
    op.create_index(op.f("ix_edges_relation_type"), "edges", ["relation_type"], unique=False)
    op.create_index("ix_edges_to", "edges", ["to_node", "relation_type"], unique=False)
    op.create_table(
        "figures",
        sa.Column("figure_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.BigInteger(), nullable=False),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("bbox", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("file_path", sa.Text(), nullable=True),
        sa.Column("thumbnail_path", sa.Text(), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("alt_text", sa.Text(), nullable=True),
        sa.Column("vlm_description", sa.Text(), nullable=True),
        sa.Column("ocr_text", sa.Text(), nullable=True),
        sa.Column("linked_entity_ids", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
            name=op.f("fk_figures_source_id_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("figure_id", name=op.f("pk_figures")),
    )
    op.create_index(op.f("ix_figures_created_at"), "figures", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_figures_created_at"), table_name="figures")
    op.drop_table("figures")
    op.drop_index("ix_edges_to", table_name="edges")
    op.drop_index(op.f("ix_edges_relation_type"), table_name="edges")
    op.drop_index(op.f("ix_edges_quality_tier"), table_name="edges")
    op.drop_index(op.f("ix_edges_produced_by"), table_name="edges")
    op.drop_index("ix_edges_from", table_name="edges")
    op.drop_index(op.f("ix_edges_created_at"), table_name="edges")
    op.drop_table("edges")
    op.drop_index("ix_chunks_id_created", table_name="chunks")
    op.drop_index(op.f("ix_chunks_created_at"), table_name="chunks")
    op.drop_table("chunks")
    op.drop_index(op.f("ix_attribute_values_quality_tier"), table_name="attribute_values")
    op.drop_index(op.f("ix_attribute_values_produced_by"), table_name="attribute_values")
    op.drop_index(op.f("ix_attribute_values_created_at"), table_name="attribute_values")
    op.drop_index("ix_attribute_values_attribute", table_name="attribute_values")
    op.drop_table("attribute_values")
    op.drop_table("topic_config")
    op.drop_index(op.f("ix_steering_log_topic"), table_name="steering_log")
    op.drop_index(op.f("ix_steering_log_changed_at"), table_name="steering_log")
    op.drop_table("steering_log")
    op.drop_index("ix_sources_tier_date", table_name="sources")
    op.drop_index(op.f("ix_sources_publication_date"), table_name="sources")
    op.drop_index(op.f("ix_sources_language"), table_name="sources")
    op.drop_index(op.f("ix_sources_doi"), table_name="sources")
    op.drop_index(op.f("ix_sources_created_at"), table_name="sources")
    op.drop_table("sources")
    op.drop_index(op.f("ix_runs_started_at"), table_name="runs")
    op.drop_table("runs")
    op.drop_index(op.f("ix_reports_created_at"), table_name="reports")
    op.drop_table("reports")
    op.drop_index("ix_queue_url_or_query", table_name="queue")
    op.drop_index(op.f("ix_queue_topic"), table_name="queue")
    op.drop_index(op.f("ix_queue_created_at"), table_name="queue")
    op.drop_index("ix_queue_claim", table_name="queue")
    op.drop_table("queue")
    op.drop_index(op.f("ix_notifications_notification_type"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_gazetteer_created_at"), table_name="gazetteer")
    op.drop_index("ix_gazetteer_canonical", table_name="gazetteer")
    op.drop_index("ix_gazetteer_approved_type", table_name="gazetteer")
    op.drop_table("gazetteer")
    op.drop_table("fetch_policy")
    op.drop_index("ix_entities_type_name", table_name="entities")
    op.drop_index(op.f("ix_entities_redirects_to"), table_name="entities")
    op.drop_index(op.f("ix_entities_quality_tier"), table_name="entities")
    op.drop_index(op.f("ix_entities_produced_by"), table_name="entities")
    op.drop_index(op.f("ix_entities_created_at"), table_name="entities")
    op.drop_table("entities")
    op.drop_index("ix_enrichment_status_type", table_name="enrichment_queue")
    op.drop_index(op.f("ix_enrichment_queue_item_type"), table_name="enrichment_queue")
    op.drop_index(op.f("ix_enrichment_queue_created_at"), table_name="enrichment_queue")
    op.drop_table("enrichment_queue")
    op.drop_index(op.f("ix_attribute_definitions_topic"), table_name="attribute_definitions")
    op.drop_index(op.f("ix_attribute_definitions_created_at"), table_name="attribute_definitions")
    op.drop_table("attribute_definitions")
    op.drop_index("ix_agents_enabled_quality", table_name="agents")
    op.drop_index(op.f("ix_agents_created_at"), table_name="agents")
    op.drop_table("agents")
    op.drop_index(op.f("ix_agent_tokens_created_at"), table_name="agent_tokens")
    op.drop_index(op.f("ix_agent_tokens_agent_id"), table_name="agent_tokens")
    op.drop_table("agent_tokens")
    # ### end Alembic commands ###
