"""fetch outcomes for the content safeguards

Adds the four outcomes worker/fetch.py produces for the P1-21 safeguards and the
P1-24 pinning refusals: unsafe_target, content_type_rejected,
decompression_bomb, too_many_redirects.

Revision ID: 28fc51373a89
Revises: 32ceada578b2
Create Date: 2026-09-06 21:51:33.583727
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "28fc51373a89"
down_revision: str | None = "32ceada578b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The bare name: the metadata naming convention expands it to
# ck_fetch_attempts_fetch_outcome on both create and drop.
CONSTRAINT = "fetch_outcome"

OLD_OUTCOMES = (
    "success",
    "not_modified",
    "http_error",
    "timeout",
    "too_large",
    "robots_denied",
    "blocked",
    "connection_error",
    "parse_error",
)

NEW_OUTCOMES = (
    *OLD_OUTCOMES,
    "unsafe_target",
    "content_type_rejected",
    "decompression_bomb",
    "too_many_redirects",
)


def _values(outcomes: tuple[str, ...]) -> str:
    return ", ".join(f"'{value}'" for value in outcomes)


def upgrade() -> None:
    # Hand-written, for the reason recorded in P0-21: Alembic autogenerate does
    # not detect CheckConstraints on an existing table. It emitted only the
    # VARCHAR length change below and left the CHECK alone — which would have
    # produced a column wide enough for the new values and a constraint that
    # still rejected every one of them, with nothing failing until the first
    # unsafe target was refused in production.
    op.drop_constraint(CONSTRAINT, "fetch_attempts", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fetch_attempts",
        "outcome",
        existing_type=sa.VARCHAR(length=16),
        type_=sa.Enum(
            *NEW_OUTCOMES,
            name="fetch_outcome",
            native_enum=False,
            create_constraint=False,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###

    op.create_check_constraint(
        "fetch_outcome", "fetch_attempts", f"outcome IN ({_values(NEW_OUTCOMES)})"
    )


def downgrade() -> None:
    op.drop_constraint(CONSTRAINT, "fetch_attempts", type_="check")

    # Rows carrying a since-removed outcome would violate the narrower
    # constraint. They are evidence of refusals that really happened, so they
    # are folded into the bucket they would have used before this migration
    # rather than deleted.
    op.execute(
        "UPDATE fetch_attempts SET outcome = 'blocked' "
        f"WHERE outcome NOT IN ({_values(OLD_OUTCOMES)})"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fetch_attempts",
        "outcome",
        existing_type=sa.Enum(
            *NEW_OUTCOMES,
            name="fetch_outcome",
            native_enum=False,
            create_constraint=False,
        ),
        type_=sa.VARCHAR(length=16),
        existing_nullable=False,
    )
    # ### end Alembic commands ###

    op.create_check_constraint(
        "fetch_outcome", "fetch_attempts", f"outcome IN ({_values(OLD_OUTCOMES)})"
    )
