"""which diversity mechanism wrote a query (task P5-05)

One nullable column with a CHECK, no default: adding it rewrites nothing, and
every existing row reads as "no mechanism recorded", which is true.

Revision ID: d6faafb2e712
Revises: 2926b43adc44
Create Date: 2026-09-24 22:14:50.190399
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d6faafb2e712"
down_revision: str | None = "2926b43adc44"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "queue",
        sa.Column(
            "seed_mechanism",
            sa.Enum(
                "counter_seed",
                "tier_imbalance",
                "naive_phrasing",
                "distant_walk",
                "non_english",
                name="seed_mechanism",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("queue", "seed_mechanism")
    # ### end Alembic commands ###
