"""queue lease and backoff

Revision ID: 32ceada578b2
Revises: 263d946f2b89
Create Date: 2026-09-06 19:54:23.443296
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "32ceada578b2"
down_revision: str | None = "263d946f2b89"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("queue", sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("queue", sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("queue", sa.Column("claimed_by", sa.Text(), nullable=True))
    op.drop_index(op.f("ix_queue_claim"), table_name="queue")
    op.create_index(
        "ix_queue_claim",
        "queue",
        ["status", "priority", "created_at", "next_attempt_at"],
        unique=False,
    )
    op.create_index(op.f("ix_queue_claimed_at"), "queue", ["claimed_at"], unique=False)
    op.create_index(op.f("ix_queue_next_attempt_at"), "queue", ["next_attempt_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_queue_next_attempt_at"), table_name="queue")
    op.drop_index(op.f("ix_queue_claimed_at"), table_name="queue")
    op.drop_index("ix_queue_claim", table_name="queue")
    op.create_index(
        op.f("ix_queue_claim"), "queue", ["status", "priority", "created_at"], unique=False
    )
    op.drop_column("queue", "claimed_by")
    op.drop_column("queue", "claimed_at")
    op.drop_column("queue", "next_attempt_at")
    # ### end Alembic commands ###
