"""chat threads and messages, and the local chat agent (tasks P6-06, P6-07)

The agent row is inserted here as well as seeded from config/agents.yaml, because
the config seeds a database at first boot only and an existing one would never
see it. Disabled, and its model and endpoint name variables (`${LOCAL_CHAT_MODEL}`,
`${LOCAL_CHAT_LLM_URL}`) resolved at call time, so nothing here names a model.

Revision ID: 0f94609cd9c7
Revises: e5b9c3d7f2a8
Create Date: 2026-09-27 21:10:47.543551
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0f94609cd9c7"
down_revision: str | None = "e5b9c3d7f2a8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_threads",
        sa.Column("thread_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("thread_id", name=op.f("pk_chat_threads")),
    )
    op.create_index(
        op.f("ix_chat_threads_created_at"), "chat_threads", ["created_at"], unique=False
    )
    op.create_index("ix_chat_threads_updated", "chat_threads", ["updated_at"], unique=False)
    op.create_table(
        "chat_messages",
        sa.Column("message_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("thread_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "user", "assistant", name="chat_role", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("context_entity_ids", postgresql.ARRAY(sa.BigInteger()), nullable=True),
        sa.Column("citations", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("nodes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("agent_id", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["chat_threads.thread_id"],
            name=op.f("fk_chat_messages_thread_id_chat_threads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("message_id", name=op.f("pk_chat_messages")),
    )
    op.create_index(
        op.f("ix_chat_messages_created_at"), "chat_messages", ["created_at"], unique=False
    )
    op.create_index(
        "ix_chat_messages_thread", "chat_messages", ["thread_id", "message_id"], unique=False
    )
    # ### end Alembic commands ###
    op.execute(
        """
        INSERT INTO agents (agent_id, provider, model, task_types, token_scope, cost_tier,
                            quality_tier, max_context, enabled, endpoint, availability)
        VALUES ('local-chat', 'openai_compatible', '${LOCAL_CHAT_MODEL}', ARRAY['chat'],
                'read', 'free', 2, NULL, false, '${LOCAL_CHAT_LLM_URL}', 'opportunistic')
        ON CONFLICT (agent_id) DO NOTHING
        """
    )


def downgrade() -> None:
    op.execute("DELETE FROM agents WHERE agent_id = 'local-chat'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_chat_messages_thread", table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_created_at"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index("ix_chat_threads_updated", table_name="chat_threads")
    op.drop_index(op.f("ix_chat_threads_created_at"), table_name="chat_threads")
    op.drop_table("chat_threads")
    # ### end Alembic commands ###
