"""host scores for the frontier (task B-48)

`host_scores` is derived by `worker.hostscore` and read by the fetch loop. And
the timetable row, since `scripts/seed.py` is insert-only.

Revision ID: 68fd9387a022
Revises: 11c2589fddbf
Create Date: 2026-09-24 19:36:41.509507
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "68fd9387a022"
down_revision: str | None = "11c2589fddbf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "host_scores",
        sa.Column("host", sa.Text(), nullable=False),
        sa.Column("examined", sa.Integer(), nullable=False),
        sa.Column("on_topic", sa.Integer(), nullable=False),
        sa.Column("pending", sa.Integer(), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("host", name=op.f("pk_host_scores")),
    )
    # ### end Alembic commands ###

    op.execute(
        """
        INSERT INTO scheduled_jobs (name, module, args, interval_seconds, enabled)
        VALUES ('hostscore', 'worker.hostscore', ARRAY['--once'], 3600, true)
        ON CONFLICT (name) DO NOTHING
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DELETE FROM scheduled_jobs
         WHERE name = 'hostscore' AND module = 'worker.hostscore' AND args = ARRAY['--once']
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("host_scores")
    # ### end Alembic commands ###
