"""what a search query yielded (task B-56)

Revision ID: f5b9328b0df8
Revises: 4870251e4296
Create Date: 2026-09-24 21:28:10.717504
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f5b9328b0df8"
down_revision: str | None = "4870251e4296"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("queue", sa.Column("search_results", sa.Integer(), nullable=True))
    op.add_column("queue", sa.Column("search_queued", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("queue", "search_queued")
    op.drop_column("queue", "search_results")
    # ### end Alembic commands ###
