"""the novelty gate records its verdict

Three columns rather than a delete (task P2-03, spec §6.1, §5.4, §12.5). §6.1
says "drop if >0.95" and §5.4 says a near-duplicate loses its raw file, but a
gate that deleted could report no pass rate, could not be re-run when the
threshold moved, and would leave nothing to audit. The gate writes a verdict;
the retention sweep (`P1-31`) is what spends it.

``duplicate_of`` is self-referential and ``ON DELETE SET NULL``, not CASCADE: if
a re-crawl deletes the survivor, the chunk pointing at it is now the only copy
of that text, and cascading would lose the content entirely.

Revision ID: 7e8b0034d0f1
Revises: 0aafb65688cf
Create Date: 2026-09-08 09:56:33.763524
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7e8b0034d0f1"
down_revision: str | None = "0aafb65688cf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chunks", sa.Column("novelty_checked_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("chunks", sa.Column("nearest_similarity", sa.Float(), nullable=True))
    op.add_column("chunks", sa.Column("duplicate_of", sa.BigInteger(), nullable=True))
    op.create_index(op.f("ix_chunks_duplicate_of"), "chunks", ["duplicate_of"], unique=False)
    op.create_index(
        "ix_chunks_novelty_pending",
        "chunks",
        ["chunk_id"],
        unique=False,
        postgresql_where=sa.text("embedding IS NOT NULL AND novelty_checked_at IS NULL"),
    )
    op.create_foreign_key(
        op.f("fk_chunks_duplicate_of_chunks"),
        "chunks",
        "chunks",
        ["duplicate_of"],
        ["chunk_id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_chunks_duplicate_of_chunks"), "chunks", type_="foreignkey")
    op.drop_index(
        "ix_chunks_novelty_pending",
        table_name="chunks",
        postgresql_where=sa.text("embedding IS NOT NULL AND novelty_checked_at IS NULL"),
    )
    op.drop_index(op.f("ix_chunks_duplicate_of"), table_name="chunks")
    op.drop_column("chunks", "duplicate_of")
    op.drop_column("chunks", "nearest_similarity")
    op.drop_column("chunks", "novelty_checked_at")
    # ### end Alembic commands ###
