"""areas: the corpus as nested clusters (task P6-30)

And the timetable row, because `scripts/seed.py` is insert-only and a
database seeded before this revision would otherwise never build areas.

Revision ID: e7ea586f5d02
Revises: 63509269e4e1
Create Date: 2026-09-24 21:26:18.810400
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e7ea586f5d02"
down_revision: str | None = "63509269e4e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "area_builds",
        sa.Column("build_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("passages", sa.Integer(), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("build_id", name=op.f("pk_area_builds")),
    )
    op.create_table(
        "areas",
        sa.Column("area_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("build_id", sa.BigInteger(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.BigInteger(), nullable=True),
        sa.Column("terms", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("passages", sa.Integer(), nullable=False),
        sa.Column("sources", sa.Integer(), nullable=False),
        sa.Column("tier_mix", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("newest_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("centroid", pgvector.sqlalchemy.Vector(1024), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["area_builds.build_id"],
            name=op.f("fk_areas_build_id_area_builds"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["areas.area_id"],
            name=op.f("fk_areas_parent_id_areas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("area_id", name=op.f("pk_areas")),
    )
    op.create_index("ix_areas_build_level", "areas", ["build_id", "level"], unique=False)
    op.create_table(
        "area_members",
        sa.Column("build_id", sa.BigInteger(), nullable=False),
        sa.Column("chunk_id", sa.BigInteger(), nullable=False),
        sa.Column("area_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["area_id"],
            ["areas.area_id"],
            name=op.f("fk_area_members_area_id_areas"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["area_builds.build_id"],
            name=op.f("fk_area_members_build_id_area_builds"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["chunks.chunk_id"],
            name=op.f("fk_area_members_chunk_id_chunks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("build_id", "chunk_id", name=op.f("pk_area_members")),
    )
    op.create_index(op.f("ix_area_members_area_id"), "area_members", ["area_id"], unique=False)
    # ### end Alembic commands ###

    op.execute(
        """
        INSERT INTO scheduled_jobs (name, module, args, interval_seconds, enabled)
        VALUES ('areas', 'worker.areas', ARRAY['--once'], 86400, true)
        ON CONFLICT (name) DO NOTHING
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DELETE FROM scheduled_jobs
         WHERE name = 'areas' AND module = 'worker.areas' AND args = ARRAY['--once']
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_area_members_area_id"), table_name="area_members")
    op.drop_table("area_members")
    op.drop_index("ix_areas_build_level", table_name="areas")
    op.drop_table("areas")
    op.drop_table("area_builds")
    # ### end Alembic commands ###
