"""bridges between areas (task P6-31)

Derived with each area build and pruned with it (ON DELETE CASCADE from the
build), so there is nothing to backfill: the next `worker.areas` run fills it.

Revision ID: 2926b43adc44
Revises: e7ea586f5d02
Create Date: 2026-09-24 22:16:17.368606
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "2926b43adc44"
down_revision: str | None = "e7ea586f5d02"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "area_bridges",
        sa.Column("bridge_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("build_id", sa.BigInteger(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("area_a", sa.BigInteger(), nullable=False),
        sa.Column("area_b", sa.BigInteger(), nullable=False),
        sa.Column("similarity", sa.Float(), nullable=False),
        sa.Column("cited_edge_ids", postgresql.ARRAY(sa.BigInteger()), nullable=False),
        sa.Column("cited_sources", sa.Integer(), nullable=False),
        sa.Column("similar_pairs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("shared_terms", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.CheckConstraint("area_a < area_b", name=op.f("ck_area_bridges_ordered")),
        sa.ForeignKeyConstraint(
            ["area_a"],
            ["areas.area_id"],
            name=op.f("fk_area_bridges_area_a_areas"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["area_b"],
            ["areas.area_id"],
            name=op.f("fk_area_bridges_area_b_areas"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["area_builds.build_id"],
            name=op.f("fk_area_bridges_build_id_area_builds"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("bridge_id", name=op.f("pk_area_bridges")),
        sa.UniqueConstraint("area_a", "area_b", name=op.f("uq_area_bridges_area_a")),
    )
    op.create_index(
        "ix_area_bridges_build_level", "area_bridges", ["build_id", "level"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_area_bridges_build_level", table_name="area_bridges")
    op.drop_table("area_bridges")
    # ### end Alembic commands ###
