"""steering proposals that apply by default (task P6-38)

`steering_proposals`, `steering_proposal` as a notification type, the hourly
timetable row for `worker.steerproposals`, and `steering_proposal_window_hours`
in the global policy row where it is absent (§13.1: the database, not the YAML,
is authoritative on a running install).

The notification CHECK is rewritten by hand: autogenerate does not see a CHECK
on an existing table (handover, "Alembic does not see CHECK constraints").

Revision ID: 63509269e4e1
Revises: b3f1c7d2e8a4
Create Date: 2026-09-24 22:16:21.799212
"""

from __future__ import annotations

import json
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "63509269e4e1"
down_revision: str | None = "b3f1c7d2e8a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Mirrors `steering_proposal_window_hours` in `config/fetch_policy.yaml` and
#: `DEFAULT_WINDOW_HOURS` in `meridian_core.steering_proposals`; a drift test
#: holds the three together.
WINDOW_HOURS = 12

#: Mirrors the `steerproposals` entry in `config/schedule.yaml`; a drift test
#: holds the two together.
JOB = ("steerproposals", "worker.steerproposals", ["--once"], 3600)

#: Expanded by the naming convention to ck_notifications_notification_type.
CONSTRAINT = "notification_type"
OLD_TYPES = (
    "run_summary",
    "job_complete",
    "alert",
    "seed_proposal",
    "gazetteer_proposal",
    "merge_adjudication",
)
NEW_TYPES = (*OLD_TYPES, "steering_proposal")


def _values(types: tuple[str, ...]) -> str:
    return ", ".join(f"'{t}'" for t in types)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "steering_proposals",
        sa.Column("proposal_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("actor", sa.Text(), nullable=False),
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "boost", "weight", name="proposal_kind", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("current_value", sa.Float(), nullable=False),
        sa.Column("proposed_value", sa.Float(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "evidence",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("apply_after", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "rejected",
                "applied",
                "superseded",
                "failed",
                name="proposal_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("decided_by", sa.Text(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind <> 'boost' OR expires_at IS NOT NULL",
            name=op.f("ck_steering_proposals_boost_expires"),
        ),
        sa.CheckConstraint(
            "kind <> 'boost' OR proposed_value > 0",
            name=op.f("ck_steering_proposals_boost_factor_positive"),
        ),
        sa.CheckConstraint(
            "kind <> 'weight' OR (proposed_value >= 0 AND proposed_value <= 1)",
            name=op.f("ck_steering_proposals_weight_is_a_share"),
        ),
        sa.CheckConstraint(
            "status <> 'applied' OR applied_at IS NOT NULL",
            name=op.f("ck_steering_proposals_applied_has_a_time"),
        ),
        sa.ForeignKeyConstraint(
            ["topic"],
            ["topic_config.topic"],
            name=op.f("fk_steering_proposals_topic_topic_config"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("proposal_id", name=op.f("pk_steering_proposals")),
    )
    op.create_index(
        op.f("ix_steering_proposals_created_at"), "steering_proposals", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_steering_proposals_topic"), "steering_proposals", ["topic"], unique=False
    )
    op.create_index(
        "uq_steering_proposals_one_pending",
        "steering_proposals",
        ["topic", "kind"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    # ### end Alembic commands ###

    op.drop_constraint(CONSTRAINT, "notifications", type_="check")
    op.create_check_constraint(
        CONSTRAINT, "notifications", f"notification_type IN ({_values(NEW_TYPES)})"
    )

    op.execute(
        sa.text(
            """
            UPDATE fetch_policy
               SET settings = jsonb_set(
                       COALESCE(settings, '{}'::jsonb),
                       '{steering_proposal_window_hours}',
                       CAST(:hours AS jsonb))
             WHERE domain = '*'
               AND NOT (COALESCE(settings, '{}'::jsonb) ? 'steering_proposal_window_hours')
            """
        ).bindparams(hours=json.dumps(WINDOW_HOURS))
    )
    name, module, args, interval = JOB
    op.execute(
        sa.text(
            """
            INSERT INTO scheduled_jobs (name, module, args, interval_seconds, enabled)
            VALUES (:name, :module, :args, :interval, true)
            ON CONFLICT (name) DO NOTHING
            """
        ).bindparams(name=name, module=module, args=args, interval=interval)
    )


def downgrade() -> None:
    name, module, args, _ = JOB
    op.execute(
        sa.text(
            "DELETE FROM scheduled_jobs WHERE name = :name AND module = :module AND args = :args"
        ).bindparams(name=name, module=module, args=args)
    )
    op.execute(
        "UPDATE fetch_policy SET settings = settings - 'steering_proposal_window_hours' "
        "WHERE domain = '*'"
    )
    # A notification of the new type cannot survive the old constraint. It
    # points at a proposal this downgrade is about to drop, so it goes too.
    op.execute("DELETE FROM notifications WHERE notification_type = 'steering_proposal'")
    op.drop_constraint(CONSTRAINT, "notifications", type_="check")
    op.create_check_constraint(
        CONSTRAINT, "notifications", f"notification_type IN ({_values(OLD_TYPES)})"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_steering_proposals_one_pending",
        table_name="steering_proposals",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(op.f("ix_steering_proposals_topic"), table_name="steering_proposals")
    op.drop_index(op.f("ix_steering_proposals_created_at"), table_name="steering_proposals")
    op.drop_table("steering_proposals")
    # ### end Alembic commands ###
