"""which embedding view a vector was computed from

Revision ID: 11c2589fddbf
Revises: 1654b2103e5a
Create Date: 2026-09-24 19:23:21.772538
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "11c2589fddbf"
down_revision: str | None = "1654b2103e5a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chunks", sa.Column("embedding_view", sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chunks", "embedding_view")
    # ### end Alembic commands ###
