"""chunks gain a lexical index

Task P2-05. The lexical half of §12.5's hybrid retrieval: a STORED generated
``tsvector`` over ``chunks.text`` plus the GIN index that makes it searchable.

Hand-written rather than autogenerated. Autogenerate does not reliably emit
``Computed`` on an added column, and a ``search_vector`` that landed as an
ordinary nullable column would be created empty, stay empty, and report every
query as "no lexical matches" — which is indistinguishable from a corpus that
genuinely does not contain the term.

``to_tsvector('english', ...)`` names its configuration because the one-argument
form reads ``default_text_search_config``, a session GUC, and is therefore not
IMMUTABLE — Postgres refuses it in a generated column. Naming it also pins the
stemming, so the same text cannot index differently depending on who connected.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import TSVECTOR

revision: str = "c1e58a3f9b02"
down_revision: str | None = "3d7b422a25e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

GENERATION = "to_tsvector('english', text)"
INDEX = "ix_chunks_search_vector"


def upgrade() -> None:
    # Existing rows are computed by the ADD COLUMN itself, so there is no
    # backfill pass here and no window where a chunk is present but unindexed.
    op.add_column(
        "chunks",
        sa.Column(
            "search_vector",
            TSVECTOR,
            sa.Computed(GENERATION, persisted=True),
            nullable=False,
        ),
    )
    op.create_index(INDEX, "chunks", ["search_vector"], postgresql_using="gin")


def downgrade() -> None:
    op.drop_index(INDEX, table_name="chunks")
    op.drop_column("chunks", "search_vector")
