"""document-level duplicates (task B-44)

`sources.duplicate_of` and its reason, with two CHECKs written by hand:
autogenerate does not see CHECK constraints added to an existing table (see
the handover), and a drift test compares them with the model.

Revision ID: 7fbdd2242063
Revises: 92cba253bcb9
Create Date: 2026-09-24 20:56:32.472452
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7fbdd2242063"
down_revision: str | None = "92cba253bcb9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sources", sa.Column("duplicate_of", sa.BigInteger(), nullable=True))
    op.add_column("sources", sa.Column("duplicate_reason", sa.Text(), nullable=True))
    op.create_index(op.f("ix_sources_duplicate_of"), "sources", ["duplicate_of"], unique=False)
    op.create_foreign_key(
        op.f("fk_sources_duplicate_of_sources"),
        "sources",
        "sources",
        ["duplicate_of"],
        ["source_id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
    op.create_check_constraint(
        op.f("ck_sources_duplicate_is_another_source"),
        "sources",
        "duplicate_of IS NULL OR duplicate_of <> source_id",
    )
    op.create_check_constraint(
        op.f("ck_sources_duplicate_has_a_reason"),
        "sources",
        "(duplicate_of IS NULL) = (duplicate_reason IS NULL)",
    )


def downgrade() -> None:
    op.drop_constraint(op.f("ck_sources_duplicate_has_a_reason"), "sources", type_="check")
    op.drop_constraint(op.f("ck_sources_duplicate_is_another_source"), "sources", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_sources_duplicate_of_sources"), "sources", type_="foreignkey")
    op.drop_index(op.f("ix_sources_duplicate_of"), table_name="sources")
    op.drop_column("sources", "duplicate_reason")
    op.drop_column("sources", "duplicate_of")
    # ### end Alembic commands ###
