"""fetch attempt log

Revision ID: 1577e06bbc96
Revises: 6d49a86ff340
Create Date: 2026-09-06 19:31:38.398938
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1577e06bbc96"
down_revision: str | None = "6d49a86ff340"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fetch_attempts",
        sa.Column("attempt_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.BigInteger(), nullable=True),
        sa.Column("domain", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "outcome",
            sa.Enum(
                "success",
                "not_modified",
                "http_error",
                "timeout",
                "too_large",
                "robots_denied",
                "blocked",
                "connection_error",
                "parse_error",
                name="fetch_outcome",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("bytes_fetched", sa.Integer(), nullable=True),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["queue.task_id"],
            name=op.f("fk_fetch_attempts_task_id_queue"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("attempt_id", name=op.f("pk_fetch_attempts")),
    )
    op.create_index(
        op.f("ix_fetch_attempts_attempted_at"), "fetch_attempts", ["attempted_at"], unique=False
    )
    op.create_index(
        "ix_fetch_attempts_domain_time", "fetch_attempts", ["domain", "attempted_at"], unique=False
    )
    op.create_index(
        "ix_fetch_attempts_outcome_time",
        "fetch_attempts",
        ["outcome", "attempted_at"],
        unique=False,
    )
    op.create_index(op.f("ix_fetch_attempts_task_id"), "fetch_attempts", ["task_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fetch_attempts_task_id"), table_name="fetch_attempts")
    op.drop_index("ix_fetch_attempts_outcome_time", table_name="fetch_attempts")
    op.drop_index("ix_fetch_attempts_domain_time", table_name="fetch_attempts")
    op.drop_index(op.f("ix_fetch_attempts_attempted_at"), table_name="fetch_attempts")
    op.drop_table("fetch_attempts")
    # ### end Alembic commands ###
