"""comparison edges must state their limits

Revision ID: 184cb19f9f1b
Revises: b29eccd3b9d1
Create Date: 2026-09-06 19:14:16.061947
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "184cb19f9f1b"
down_revision: str | None = "b29eccd3b9d1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Hand-written: Alembic autogenerate does not detect CheckConstraints added
    # to an existing table, so these must be emitted explicitly or they exist
    # only in the model and never in the database.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("edges", sa.Column("similarity_dimension", sa.Text(), nullable=True))
    op.add_column("edges", sa.Column("disanalogy", sa.Text(), nullable=True))
    # ### end Alembic commands ###

    op.create_check_constraint(
        "valid_period_ordered",
        "edges",
        "valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from",
    )
    op.create_check_constraint(
        "comparison_states_its_limits",
        "edges",
        "relation_type <> 'comparable_to' "
        "OR (similarity_dimension IS NOT NULL AND disanalogy IS NOT NULL)",
    )


def downgrade() -> None:
    op.drop_constraint("comparison_states_its_limits", "edges", type_="check")
    op.drop_constraint("valid_period_ordered", "edges", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("edges", "disanalogy")
    op.drop_column("edges", "similarity_dimension")
    # ### end Alembic commands ###
