"""http cache validators on sources

Revision ID: 0aafb65688cf
Revises: 28fc51373a89
Create Date: 2026-09-06 22:13:59.894591
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0aafb65688cf"
down_revision: str | None = "28fc51373a89"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sources", sa.Column("etag", sa.Text(), nullable=True))
    op.add_column("sources", sa.Column("last_modified", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sources", "last_modified")
    op.drop_column("sources", "etag")
    # ### end Alembic commands ###
