"""the page that cited a DOI (task B-58)

Revision ID: 740a4f79888c
Revises: d6faafb2e712
Create Date: 2026-09-24 21:49:38.455318
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "740a4f79888c"
down_revision: str | None = "d6faafb2e712"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("queue", sa.Column("parent_source_id", sa.BigInteger(), nullable=True))
    op.create_index(op.f("ix_queue_parent_source_id"), "queue", ["parent_source_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_queue_parent_source_id_sources"),
        "queue",
        "sources",
        ["parent_source_id"],
        ["source_id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
    # The pass that ranks queued DOIs by the page that cited them, on the
    # timetable but disabled: read its first report, then enable it in Admin.
    op.execute(
        """
        INSERT INTO scheduled_jobs (name, module, args, interval_seconds, enabled)
        VALUES ('requeue_dois', 'worker.requeue_dois', ARRAY['--apply'], 3600, false)
        ON CONFLICT (name) DO NOTHING
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DELETE FROM scheduled_jobs
         WHERE name = 'requeue_dois' AND module = 'worker.requeue_dois'
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_queue_parent_source_id_sources"), "queue", type_="foreignkey")
    op.drop_index(op.f("ix_queue_parent_source_id"), table_name="queue")
    op.drop_column("queue", "parent_source_id")
    # ### end Alembic commands ###
