"""observation qualifiers

Revision ID: 6d49a86ff340
Revises: 184cb19f9f1b
Create Date: 2026-09-06 19:18:17.139282
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "6d49a86ff340"
down_revision: str | None = "184cb19f9f1b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "observations",
        sa.Column("qualifiers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.create_index(
        "ix_observations_qualifiers",
        "observations",
        ["qualifiers"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_observations_qualifiers", table_name="observations", postgresql_using="gin")
    op.drop_column("observations", "qualifiers")
    # ### end Alembic commands ###
