"""other-language names for the search vocabulary (task B-52)

`translation_lookups`, the timetable row for `worker.translate`, and
`search_languages` in the global policy row where it is absent (§13.1: the
database, not the YAML, is authoritative on a running install).

Revision ID: 92cba253bcb9
Revises: 5c15e30affb6
Create Date: 2026-09-24 20:39:34.358669
"""

from __future__ import annotations

import json
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "92cba253bcb9"
down_revision: str | None = "5c15e30affb6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


#: Mirrors `search_languages` in `config/fetch_policy.yaml`; a drift test holds
#: the two together.
SEARCH_LANGUAGES = ["ja", "ko", "zh", "de", "fr", "nl", "id", "ms", "th"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "translation_lookups",
        sa.Column("phrase", sa.Text(), nullable=False),
        sa.Column("article", sa.Text(), nullable=True),
        sa.Column(
            "translations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "looked_up_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("phrase", name=op.f("pk_translation_lookups")),
    )
    # ### end Alembic commands ###

    op.execute(
        sa.text(
            """
            UPDATE fetch_policy
               SET settings = jsonb_set(settings, '{search_languages}', CAST(:langs AS jsonb))
             WHERE domain = '*' AND NOT (settings ? 'search_languages')
            """
        ).bindparams(langs=json.dumps(SEARCH_LANGUAGES))
    )
    op.execute(
        """
        INSERT INTO scheduled_jobs (name, module, args, interval_seconds, enabled)
        VALUES ('translate', 'worker.translate', ARRAY['--once'], 86400, true)
        ON CONFLICT (name) DO NOTHING
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DELETE FROM scheduled_jobs
         WHERE name = 'translate' AND module = 'worker.translate' AND args = ARRAY['--once']
        """
    )
    op.execute("UPDATE fetch_policy SET settings = settings - 'search_languages' WHERE domain = '*'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("translation_lookups")
    # ### end Alembic commands ###
