"""boilerplate lines per host (task B-43)

`page_lines` holds each page's line hashes from uncleaned text;
`boilerplate_lines` is derived from it by `worker.boilerplate`. And the
timetable row, because `scripts/seed.py` is insert-only and a database seeded
before this revision would otherwise never run the pass.

Revision ID: 1654b2103e5a
Revises: 71de4a6d0c50
Create Date: 2026-09-24 19:01:00.216108
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1654b2103e5a"
down_revision: str | None = "71de4a6d0c50"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "boilerplate_lines",
        sa.Column("host", sa.Text(), nullable=False),
        sa.Column("line_hash", sa.BigInteger(), nullable=False),
        sa.Column("pages", sa.Integer(), nullable=False),
        sa.Column("host_pages", sa.Integer(), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("host", "line_hash", name=op.f("pk_boilerplate_lines")),
    )
    op.create_table(
        "page_lines",
        sa.Column("source_id", sa.BigInteger(), nullable=False),
        sa.Column("line_hash", sa.BigInteger(), nullable=False),
        sa.Column("host", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
            name=op.f("fk_page_lines_source_id_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("source_id", "line_hash", name=op.f("pk_page_lines")),
    )
    op.create_index("ix_page_lines_host_hash", "page_lines", ["host", "line_hash"], unique=False)
    # ### end Alembic commands ###

    op.execute(
        """
        INSERT INTO scheduled_jobs (name, module, args, interval_seconds, enabled)
        VALUES ('boilerplate', 'worker.boilerplate', ARRAY['--once'], 86400, true)
        ON CONFLICT (name) DO NOTHING
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DELETE FROM scheduled_jobs
         WHERE name = 'boilerplate' AND module = 'worker.boilerplate'
           AND args = ARRAY['--once']
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_page_lines_host_hash", table_name="page_lines")
    op.drop_table("page_lines")
    op.drop_table("boilerplate_lines")
    # ### end Alembic commands ###
