"""jurisdiction and ambiguity scoping

Revision ID: 263d946f2b89
Revises: 1577e06bbc96
Create Date: 2026-09-06 19:45:05.932714
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "263d946f2b89"
down_revision: str | None = "1577e06bbc96"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entities", sa.Column("jurisdiction", sa.Text(), nullable=True))
    op.drop_constraint(op.f("uq_entities_canonical_name_type"), "entities", type_="unique")
    op.drop_index(op.f("ix_entities_type_name"), table_name="entities")
    op.create_index(
        "ix_entities_type_name",
        "entities",
        ["node_type", "canonical_name", "jurisdiction"],
        unique=False,
    )
    op.create_index(op.f("ix_entities_jurisdiction"), "entities", ["jurisdiction"], unique=False)
    op.create_unique_constraint(
        "uq_entities_canonical_name_type_jurisdiction",
        "entities",
        ["canonical_name", "node_type", "jurisdiction"],
    )
    op.add_column("gazetteer", sa.Column("jurisdiction", sa.Text(), nullable=True))
    op.add_column(
        "gazetteer",
        sa.Column("ambiguous", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.drop_index(op.f("ix_gazetteer_canonical"), table_name="gazetteer")
    op.create_index("ix_gazetteer_canonical", "gazetteer", ["canonical"], unique=False)
    op.create_index(op.f("ix_gazetteer_jurisdiction"), "gazetteer", ["jurisdiction"], unique=False)
    op.create_unique_constraint(
        "uq_gazetteer_term_scope", "gazetteer", ["canonical", "jurisdiction", "entity_type"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_gazetteer_term_scope", "gazetteer", type_="unique")
    op.drop_index(op.f("ix_gazetteer_jurisdiction"), table_name="gazetteer")
    op.drop_index("ix_gazetteer_canonical", table_name="gazetteer")
    op.create_index(op.f("ix_gazetteer_canonical"), "gazetteer", ["canonical"], unique=True)
    op.drop_column("gazetteer", "ambiguous")
    op.drop_column("gazetteer", "jurisdiction")
    op.drop_constraint("uq_entities_canonical_name_type_jurisdiction", "entities", type_="unique")
    op.drop_index(op.f("ix_entities_jurisdiction"), table_name="entities")
    op.drop_index("ix_entities_type_name", table_name="entities")
    op.create_index(
        op.f("ix_entities_type_name"), "entities", ["node_type", "canonical_name"], unique=False
    )
    op.create_unique_constraint(
        op.f("uq_entities_canonical_name_type"),
        "entities",
        ["canonical_name", "node_type"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("entities", "jurisdiction")
    # ### end Alembic commands ###
